# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jianshi Huang's Homepage
tagline:          Powered by Poole & Jekyll
url:              http://huangjs.github.io
paginate:         5
baseurl:          /
author:
  name:           Jianshi Huang
  url:            https://weibo.com/huangjianshi
  email:          jianshi.huang@gmail.com

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/huangjs/huangjs.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
